# Generated by Django 5.1.1 on 2025-12-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
