# Generated by Django 5.1.1 on 2025-11-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_profile_address_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
