# Generated by Django 5.1.1 on 2025-12-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_enrollment_rejection_reason_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='enrollment/resume/'),
        ),
    ]
