# Generated by Django 5.1.1 on 2025-12-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_enrolment_delete_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
